# Generated by Django 4.0.4 on 2022-04-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('duration', models.CharField(max_length=32)),
                ('overview', models.CharField(max_length=300)),
                ('activities', models.CharField(max_length=500)),
            ],
        ),
    ]
